name: CI/CD

on:
  push:
    branches: [ "cicd_307954" ]

jobs:
  windows-test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: python unit tests
        run: |
          python -m unittest test_circle.py
          python -m unittest test_rectangle.py
          python -m unittest test_square.py
          python -m unittest test_triangle.py

  ubuntu-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: python unit tests
        run: |
          python -m unittest test_circle.py
          python -m unittest test_rectangle.py
          python -m unittest test_square.py
          python -m unittest test_triangle.py
